### ISSUE TITLE
About using the title bar to hide the layout suggestion behind（使用“在垂直选项卡中隐藏标题栏后排版建议）”）

### ISSUE THREAD

**Issue by WoIsHuman** [microsoft/MicrosoftEdge-Extensions#100]
English：First of all forgive me for my English rubbish, so I can only use machine translation, I am sorry if it confuses your reading

Chinese：首先原谅我英语垃圾，所以只能用机器翻译，如果对您的阅读造成困惑，我深感抱歉

**Is your feature request related to a problem? Please describe.**

English：After using "Hide the title bar in the vertical tab", the typesetting layout of edge becomes very uncomfortable, as shown in the two screenshots below, when the title bar is displayed, the layout is reasonable (see the blue box in Figure 1 ), but after hiding the title bar, the blue frame area is too blank (see Figure 2), which makes the whole look ugly. Can you move the red frame area in Figure 2 to the right? This should look a little better

Chinese：使用"在垂直选项卡中隐藏标题栏"后edge的排版布局变得很让人难受，如下图中两张截图所示，在显示标题栏时，布局合理（见图一蓝色框中所示），但在隐藏标题栏后，蓝框框区域空白太大（见图二），使得整体并不好看了，能不能把图二中红色框区域向右移动？这样应该看起来会更好一点

**Describe the solution you'd like**

English：Move the red box area in Figure 2, that is, after using "Hide Title Bar" to the right, so it should look better

Chinese：将图二中，也就是使用“隐藏标题栏”后中的红色框区域向右移动，这样应该看起来会更好一点

**Describe alternatives you've considered**

English：no alternative

Chinese：暂时没有

**Additional context**

![IMG_20230811_233309](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/101498308/4c48e8da-6502-4f1d-8f51-e8382eae926e)
![IMG_20230811_233357](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/101498308/f856d0bd-ecda-4efa-b163-e18a03b5d5aa)

**Comment by WoIsHuman** [comment]
English：Add the original image

Chinese：补上原图

<img width="1280" alt="屏幕截图 2023-08-11 230543-2" src="https://github.com/microsoft/MicrosoftEdge-Extensions/assets/101498308/781f2a02-e4fc-4df8-90bd-5d1910937d54">
<img width="1280" alt="屏幕截图 2023-08-11 230557-1" src="https://github.com/microsoft/MicrosoftEdge-Extensions/assets/101498308/57aae6df-ce19-463e-bc90-dc52e0db37f4">

**Comment by Bhuvana-Priya** [comment]
We acknowledge your request and the right team will look into it.

**Comment by sivMSFT** [comment]
Hi @WoIsHuman, thank you for reaching out to us.

After analysis, we find this is a **Microsoft Edge Browser** issue, you can go ahead and share it here: https://github.com/MicrosoftEdge

Please let us know, if you need more support with Microsoft Edge Add-ons.

Thank you!
