### ISSUE TITLE
[Bug - Partner Center] [Add-ons API] Invalid JWT error

### ISSUE THREAD

**Issue by maximtop** [microsoft/MicrosoftEdge-Extensions#107]
Recently API started to throw error { "statusCode": 401, "message": "Invalid JWT." }
There is no any information about JWT, and the code used to upload updates to the store via API was the same.

**Comment by bofoy** [comment]
Started seeing this issue tuesday as well. A jwt is returned from the oauth endpoint but using that JWT returns the same "invalid JWT" message. Inspecting the jwt (through jwt.io) shows the payload section with broken characters.

**Comment by wdzeng** [comment]
The API is still working on Aug 28th. The first time I found the issue is Aug 30th.

**Comment by wdzeng** [comment]
The issue seems to have been fixed.

**Comment by maximtop** [comment]
I confirm

**Comment by Bhuvana-Priya** [comment]
Thank you for the confirmation @wdzeng , @maximtop. Closing the bug.
