### ISSUE TITLE
Background permission and error in windows.create()

### ISSUE THREAD

**Issue by aropb** [microsoft/MicrosoftEdge-Extensions#109]
I am using the "background" permission in the MV3 extension. When the browser is closed, the windows.create() method is called in the tabs.onRemoved event. This works great in Chrome. 
But an error appears in Edge: "window creation is restricted in standalone sidebar mode". 

I tried disabling the policies: StandaloneHubsSidebarEnabled, HubsSidebarEnabled. It didn't help.
I don't understand what the sidebar has to do with it. This mistake just shouldn't happen!

I think this is a browser error. Is there a solution to this problem?

**Comment by Bhuvana-Priya** [comment]
Thank you for reporting this. The concerned team is aware of the issue and are looking into it. We will let you know for any update as soon as possible.

**Comment by aropb** [comment]
Do you have any news on this bug?
Thanks.

**Comment by Bhuvana-Priya** [comment]
Hi All,

This has been fixed in Edge Canary and should be working. We will let you know once it is live and fixed in Edge Stable versions as well.

**Comment by aropb** [comment]
Hi,

I see that this is fixed in the stable version 119.0.2151.44.

**Comment by jacksteamdev** [comment]
@Bhuvana-Priya This is brilliant! Kudos to the MS Edge development team!

**Comment by aropb** [comment]
Hello,
Everything is fine with us, it works (Edge 121.0.2277.112 x64).

**Comment by ChristianNoelSchmid** [comment]
Hi, thanks for the response,
Interesting - it's possible there's something else going on then.
Here's my Error output:
![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/42004356/5d3e92a1-55f3-403a-9efb-bdae6880710b)
I'll keep investigating, thank you!

**Comment by ChristianNoelSchmid** [comment]
Hi, this is still an ongoing issue for us. I was just wondering - is that error ("window creation is restricted in standalone sidebar mode") still supposed to come up under certain conditions? Am I just not setting the manifest file up correctly, or something like that?

**Comment by derline** [comment]
This issue still exists! 
My version is 122.0.2365.80.

**Comment by aropb** [comment]
We do not repeat the mistake. What are you doing to get this error?

**Comment by GaurangTandon** [comment]
I also noticed this error in Edge 124, but only a few times across thousands of users. So this issue probably happens only under some specific conditions. For example: maybe it only happens for extensions installed into Edge from the Chrome Web Store? Or only on admin controlled PCs? I'm not sure.

**Comment by derline** [comment]
> We do not repeat the mistake. What are you doing to get this error?

@GaurangTandon @aropb 
It's this extension: https://microsoftedge.microsoft.com/addons/detail/saladict-popup-diction/idghocbbahafpfhjnfhpbfbmpegphmmp
![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/6316267/bfd5c089-902d-4729-aa60-9331fa5973ab)

When I set a shortcut key for one of its functions (opening a small window) and set the response scope to "global," everything works fine as long as Edge is not closed. However, when Edge is closed and I press the shortcut key, the system prompt appears.
![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/6316267/22eb33a1-0474-4456-96dd-8a92c3a7c5ac)
Regardless of whether it's downloaded from the Chrome store or the Edge store.

**Comment by derline** [comment]
傻逼玩意
