### ISSUE TITLE
[Bug - Partner Center] Review failed

### ISSUE THREAD

**Issue by x100x-dev** [microsoft/MicrosoftEdge-Extensions#110]
The errors described there do **not relate** to my extension.
In the report you mentioned:
1. Install the product.
2. connect to a server. 
3. Notice that the product does not connect, and the IP address has not changed.

But my extension is a **Bookmarks manager**. It **doesn't have any servers to connect to**, and it certainly **doesn't change any IP addresses**.

How can I connect the review team?
The link to contact support team from this page https://docs.microsoft.com/microsoft-edge/extensions-chromium/publish/contact-extensions-team is not works...

Any way to contact the support ?

**Comment by Gurjeet-msft** [comment]
@x100x-dev Request you to please provide us more details of your extension and the submission you are referring to @ext_dev_support@microsoft.com
