### ISSUE TITLE
[Bug - Partner Center] <Missing All Sections in Sidebar under Menu on Home>

### ISSUE THREAD

**Issue by akkshayTandon** [microsoft/MicrosoftEdge-Extensions#126]
**Describe the bug**
Whenever I login to the Microsoft Partner Center, on the home page there is a navigation sidebar, but all the necessary other linked sections are missing from there namely:
- Overview: My learning profile, My access, Programs, Agreements, Edge Extension Dashboard
- Organization Profile: Legal Info, Identifiers
- Payout and Tax: Payout and tax profiles, Payout and tax profile assignment

**To Reproduce**
1. Go to [Partner Center](https://partner.microsoft.com/dashboard/v2/home?route=v2) and login.
2. Open the sidebar, See error.
OR
4. Go to My Access from the home page.
5. In the sidebar, no option to See Edge Extension published by the developer, i.e. the dashboard.

**Screenshots**
![Screenshot (168)](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/76265879/ff35fffe-6a66-468b-88af-16344e23f7ac)
![Screenshot (169)](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/76265879/8ca79c97-2565-4aac-9841-e0ca1ccc3db8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 120.0.2210.77 (Official build) (64-bit) 

**Expected behavior**
- Need To Add all the required options on Home.
- Need To Add the edge dashboard option, as mentioned above.

**Comment by ManikanthMSFT** [comment]
Hi @akkshayTandon, we are sorry for the delay in response,

Could you please confirm if you are still facing the issue?

**Comment by sandeepchads** [comment]
@akkshayTandon we are unable to repro the error. Currently it is showing us the appropriate tabs. I apologize for the inconvenience since it looks like an intermittent error. Closing this for now. 

Please report back if you see this issue occur again.

<img width="206" alt="image" src="https://github.com/microsoft/MicrosoftEdge-Extensions/assets/19730241/2695f619-9b34-4162-ab30-2faa5d94328f">

**Comment by ManikanthMSFT** [comment]
Hi @akkshayTandon, as a work around these are the steps for accessing the missing sections in sidebar under Menu on Home:

- Go to Partner Center and log in
- Click on the settings icon in the top right
- Navigate to the account settings page
- The respective sections will be visible on the left side

![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/171536664/9ee34e11-4e38-40ff-96d8-e84d462a3e2a)

Please report back if you see this issue occur.

**Comment by akkshayTandon** [comment]
Thanks for the response. I checked it and now it's better.[
![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/76265879/1a20474c-eba9-4e5b-a524-1e06d333de56)
](url)

**Comment by ManikanthMSFT** [comment]
@akkshayTandon, we’re pleased to hear that your issue has been addressed. Should you have any further queries or concerns, don’t hesitate to reach out to us.
