### ISSUE TITLE
[Bug - Partner Center] Unable to access developer dashboard

### ISSUE THREAD

**Issue by ghostwords** [microsoft/MicrosoftEdge-Extensions#130]
**Describe the bug**
Links to the developer dashboard instead end up at https://partner.microsoft.com/en-us/PageNotFound

>Sorry, we couldn't find that page.
>[Partner Center home](https://partner.microsoft.com/)
>App server:
>Time:

**To Reproduce**
1. Visit https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home
2. Click on the "Developers" menu item on the top
3. Select "Developer dashboard"
4. Log in successfully

**Expected behavior**
I get redirected to the developer dashboard.

**Comment by ghostwords** [comment]
It's working now. What happened though?

**Comment by sandeepchads** [comment]
@ghostwords Thanks for reporting this bug. We tried this on VPN and without and it seems to be working fine. Closing this as no-repro. If you still encounter this bug, then please report it back.
