### ISSUE TITLE
Expedited review for critical extension update in manifest exclusion list of websites?

### ISSUE THREAD

**Issue by yogesh-morankar** [microsoft/MicrosoftEdge-Extensions#132]
### Discussed in https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **applied-kevinsalot** May 23, 2023</sup>
Hi,
Is there a process to request an expedited review for an update to an existing Edge extension? The latest version of our extension had a misconfiguration in the manifest and we need to quickly turn around and make another update to correct it. Our customers are unable to use it in the meantime.

Is there a process to go through for this?

Thank you,</div>

**Comment by yogesh-morankar** [comment]
@sivsouvamMSFT Is there any way to expedite the review. 

We have a large 20,000 user school district requiring an urgent update for our Edge extension. The extension update (version 0.2.0.38) is extremely small and limited only to the manifest. Only several domains have been added to the "exclude_matches" of the "content_scripts" (which only reduces the extension permissions). As there should be no review requirements for this change, we ask that you please urgently approve this release so we do not delay our customer any further. The last release approval took 7 business days, and we cannot afford to have such a delay for this release. Thank you in advance for your cooperation. Much thanks.

**Comment by yogesh-morankar** [comment]
FYI @nagachaitanyalokam

**Comment by yogesh-morankar** [comment]
@nagachaitanyalokam @msftgits @msftdata @sivsouvamMSFT Can we have your attention to our urgent request to fast track the Browser extension review process for one of our critical release. It has impact on all of our business users and we need this extension to go live as soon as possible. It has very short fixes in manifest file to exclude executing the content script on selective websites.
Also let me know in case we can get on a call or location to share the more details on the extension.

**Comment by Manikanth2109** [comment]
Hi @yogesh-morankar, apologize for the delay in our response.

 We hope that your extension is now successfully live.
