### ISSUE TITLE
MS Edge crashes when user clicks a target="_blank" link in the sidepanel

### ISSUE THREAD

**Issue by twschiller** [microsoft/MicrosoftEdge-Extensions#145]
We're hitting a nasty bug where MS Edge crashes when the user clicks a `target=_blank` URL in the sidepanel:
- https://github.com/pixiebrix/pixiebrix-extension/issues/8206
- https://github.com/pixiebrix/pixiebrix-extension/issues/7809

MS Edge crashes and on next startup, our extension is no longer installed

I'm surprised other developers haven't hit up against this? Or is there an existing bug ticket

We're currently trying to reliably intercept the clicks to use `window.open` or `browser.tabs.create` instead. However, in some cases there might be a frame embedded in the side panel. Therefore, we'd have to have a contentScript to just try to intercept link clicks for any frame that might appear within the sidepanel

**Comment by mukul-p** [comment]
Ack. We will get back after investigating this.

**Comment by twschiller** [comment]
Appreciate the help! For others viewing this issue, here's our latest workaround for embedded iframes: https://github.com/pixiebrix/pixiebrix-extension/pull/8223

**Comment by twschiller** [comment]
Hi @rishikramena-ms, thanks for investigating. Here's a repository with a minimal reproduction: https://github.com/pixiebrix/msedge-crash-repro

Let me know if there's any other information I can provide!

> I tried reproducing the crash using the extension published on the Chrome Web Store but couldn't.

We've added a mitigation: https://github.com/pixiebrix/pixiebrix-extension/blob/44a3b1a8b947ec82af349779c8e4baa4435db0ac/src/utils/openAllLinksInPopups.ts#L38-L38

And are also currently working on a mitigation for embedded frames using a content script: https://github.com/pixiebrix/pixiebrix-extension/pull/8223

**Comment by twschiller** [comment]
@rishikramena-ms any updates here? This bug is preventing our customers from using MS Edge with our product

**Comment by rishikramena-ms** [comment]
Hi @twschiller,

Sorry for the delayed resolution. We are aware of this issue and have identified a fix for this. This should be resolved in a subsequent update. Will notify you on this thread once the fix is available publicly.

Thanks,
Rishik

**Comment by rishikramena-ms** [comment]
The fix is now available in canary.

**Comment by apawson** [comment]
In my case, adding `rel="opener"` to my links that also have `target="_blank"` seems to prevent the crash.
