### ISSUE TITLE
[Bug - Partner Center] No email when extension is approved

### ISSUE THREAD

**Issue by infinitepower18** [microsoft/MicrosoftEdge-Extensions#147]
**Describe the bug**
My extension update was approved but I received no email about it. I had to check the partner center manually.

**To Reproduce**
Submit an extension update for review

**Expected behavior**
An email should be sent when the update is approved. I got emails for previous submissions but not this one.

**Comment by prithamkasiMSFT** [comment]
Hi @infinitepower18 

Thank you for bringing this to our attention.

Could you please email us your Seller ID and the extension details to ext_dev_support@microsoft.com so we could investigate this issue?

**Comment by prithamkasiMSFT** [comment]
Hi @infinitepower18 

Could you please help us with your CRX ID, so we could investigate this issue?

**Comment by infinitepower18** [comment]
@prithamkasiMSFT sent an email

**Comment by prithamkasiMSFT** [comment]
Hi @infinitepower18 

Thank you for sending us the email.

I will go ahead and close the ticket here, and further communication will be continued via email. 

Thank you for your patience!
