### ISSUE TITLE
[Bug - Edge Addons] Extension demo part 2 don't work anymore with the code

### ISSUE THREAD

**Issue by MichelLaplane** [microsoft/MicrosoftEdge-Extensions#158]
When clicking on Display nothing happens and an error is visible in manage extensions 

"Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist."

**Comment by RanadhirMSFT** [comment]
Hello @MichelLaplane , could you please provide more info on this issue?
Is this occurring for any specific extension?
Are you referring to the sample extension demo file on the repository?

**Comment by MichelLaplane** [comment]
Hello @RanadhirMSFT thank you for your reply. It is only for the samples called "Create an extension tutorial, part 2" here:
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?tabs=v3
I try lot of things all yesterday with no success.
I use the  "Load unpacked" feature to test and the message appears in extension errors after clicking on display button.
![2024-06-06_10-23-32](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/15141659/4bf513ba-8ce5-414a-9c94-83cc83e398c2)
![2024-06-06_10-25-37](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/15141659/fc07f388-c69d-4e3c-8341-5a7950391100)
Thank you for your help

**Comment by RanadhirMSFT** [comment]
Thank you @MichelLaplane for clarifying this. We'll contact the right team responsible and get this fixed as soon as possible!

**Comment by utkpatdev** [comment]
@MichelLaplane, the sample extension that you are trying has no issues. You saw the error because none of the extensions can make any changes to any of Microsoft Edge's internal pages like edge://extensions or edge://settings. To test the extension, try it on any website from the internet opened in a tab in Microsoft Edge and you'll see that the extension works as expected.
