### ISSUE TITLE
[Bug - Partner Center]  Uploading new package API 500 Internal Server Error

### ISSUE THREAD

**Issue by ruwi-next** [microsoft/MicrosoftEdge-Extensions#163]
**Describe the bug**
As part of our automated publishing process we use the `/products/{productID}/submissions` API to upload our new package. This has started failing recently. Investigating this further we are getting a 500 Internal Server Error with no response back from this API.

```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Request-Context: appId=cid-v1:23f44029-850d-47f4-8c9f-200d01ff4866
< Date: Wed, 19 Jun 2024 12:35:58 GMT
```

**To Reproduce**
Run 
```bash
curl "https://api.addons.microsoftedge.microsoft.com/v1/products/${PRODUCT_ID}/submissions/draft/package" -H "${ACCESS_TOKEN}" -H "Content-Type: application/zip" -X POST -T "package.zip" -v
```

**Expected behavior**
Upload happens and returns a 2xx response code with the location header set as the docs state https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#publish-the-product-draft-submission

**Comment by ManikanthMSFT** [comment]
Hi @ruwi-next,

Thank you for reporting this. We are looking into this and will get back to you as soon as we have an update.

**Comment by ManikanthMSFT** [comment]
Hey @ruwi-next, we appreciate your patience. We just got an update from our team stating that the issue was fixed. We recommend you to please try again and contact us if you have any further concerns. Thank you.

**Comment by ruwi-next** [comment]
It is working now, thank you :)

**Comment by ManikanthMSFT** [comment]
Hi @ruwi-next, we are delighted to hear that your issue has been resolved. Should you encounter any further concerns or require additional assistance, please do not hesitate to reach out to us. We are always here to support you.
