### ISSUE TITLE
[Bug - Partner Center] Uploaded extension logo always fails validation

### ISSUE THREAD

**Issue by monyxie** [microsoft/MicrosoftEdge-Extensions#164]
**Describe the bug**
Uploading a new extension logo in Partner Center always results in the following error message:
```
Please upload a valid .png image with aspect ratio 1:1 and minimum size 128 x 128 pixels.
```

**To Reproduce**
1. Go to `https://partner.microsoft.com/en-us/dashboard/microsoftedge/${PRODUCT_ID}/listings`
2. Under "Extension log", click on "Add image"
3. Choose a PNG file of 300x300 or 128x128 size.
5. See error

**Expected behavior**
Choosen image should pass the validation and become the new extension logo.

**Screenshots**
![Screenshot from 2024-06-20 14-34-07](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/703164/89b2055d-9033-475e-b968-033b5afc52f9)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 127.0

**Additional context**
After inspecting browser network requests, I discovered that the following URL returned a `500` response.
```
https://partner.microsoft.com/en-us/dashboard/microsoftedge/api/${PRODUCT_ID}/listings/Assets/${SOME_ID}/commit
```
The response body is as follows:
```
{
  "CorrelationId": "19c9c41c-4975-499d-8a35-0e4d77b2a74b",
  "CorrelationVector": "pZR/gFhG/0S1yTjY.1",
  "Time": "20 Jun 2024 06:33:13 +00:00",
  "Status": "InternalServerError"
}
```

**Comment by ManikanthMSFT** [comment]
Hi @monyxie, thank you for reaching out and providing a detailed description of the issue you’re facing. We understand that you’re encountering an error when trying to upload a new extension logo in the Partner Center.

We’re aware of this issue and our engineering team is actively working on a fix. In the meantime, as a workaround, please try to reload the page after you encounter an error. This should allow you to successfully upload your image.

Please don’t hesitate to reach out if you have any further questions or concerns.
