### ISSUE TITLE
[Bug - Edge browser] `<select>` dropdown menu gap mouseout issue

### ISSUE THREAD

**Issue by thdoan** [microsoft/MicrosoftEdge-Extensions#168]
**Describe the bug**

In Microsoft Edge, there is a gap between the `<select>` dropdown menu and its options when you expand the menu (see screenshot below). This can lead to issues with the `mouseout` event.

**To Reproduce**

1. Go to https://jsfiddle.net/thdoan/kev4Lsha/6/
2. Select a menu option.
3. Observe the issue.

**Expected behavior**

The background should NOT change to red when you select an option, but it does because of the gap. Try following the steps above in Chrome -- you should see that Chrome dropdown menus have no such gap, hence do not suffer from this bug.

**Screenshots**

![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/4110567/964c4fb3-1e18-4294-8dc5-654524f243bd)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Edge
 - Version: 126.0.2592.68 (Official build) (64-bit)

**Comment by ManikanthMSFT** [comment]
Hi @thdoan, thank you for reaching out to us. 

We understand that you’re experiencing an issue with the Edge browser. To ensure that the appropriate team addresses your concern, we kindly request you to share the details of your issue on our feedback page: https://github.com/MicrosoftEdge/WebView2Feedback

**Comment by thdoan** [comment]
@ManikanthMSFT thanks for informing me about the proper channels to report this bug. I will re-post this there and then close this issue.

**Comment by thdoan** [comment]
Issue reported here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4646
