### ISSUE TITLE
[Support - Edge Addons] Need to change account type from individual to company

### ISSUE THREAD

**Issue by jliu1992** [microsoft/MicrosoftEdge-Extensions#171]
**Describe the bug**
By mistake we registered this account with individual, but we are publishing extensions for our company. Currently we have a blocker to update extension to achieve our requirement, and the report mentioned we need to publish with company account. 

Please share steps to change account type from individual to company. Thanks.

**Comment by ManikanthMSFT** [comment]
Hi @jliu1992, thank you for contacting us. We are looking into this and will let you know as soon as we have an update.

**Comment by ManikanthMSFT** [comment]
Hi @jliu1992, to assist you better, could you please provide more details about the specific issue you’re encountering while publishing the extension? Are there any error messages or codes that you could share?

**Comment by jliu1992** [comment]
Hi @ManikanthMSFT
Actually I have created another developer account and I want to transfer some of extensions from my previous developer account to new one.

Any steps or guidance could you please share?

**Comment by jliu1992** [comment]
> Hi @ManikanthMSFT Actually I have created another developer account and I want to transfer some of extensions from my previous developer account to new one.
> 
> Any steps or guidance could you please share?

The old account: transaction.service.cmb@outlook.com
New account: ui.ts.cmb@outlook.com

Now I want to transfer both the 2 extensions from old account into my new account.

Kindly help me with it.

Thanks so much.

**Comment by ManikanthMSFT** [comment]
Hi @jliu1992, thank you for confirming that you have created a new account. For changing your email, please contact us at ext_dev_support@microsoft.com so we can assist you efficiently.

**Comment by jliu1992** [comment]
Sure, will do, thanks so much

Closing this issue
