### ISSUE TITLE
[Bug - Add-ons API] Package upload status endpoint fails but does not provide any errors

### ISSUE THREAD

**Issue by valenvb-ag** [microsoft/MicrosoftEdge-Extensions#175]
**Describe the bug**
Since at least July 17, 2024, the package upload status endpoint (/v1/products/$productID/submissions/draft/package/operations/$operationID) described in the [documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#checking-the-status-of-a-package-upload) has been returning a `Failed` status, with no error code or errors. Eg:

```json
{"id":"<operation ID>","createdTime":"2024-07-25T19:24:34.5993321Z","lastUpdatedTime":"2024-07-25T19:24:35.5066662Z","status":"Failed","message":"An error occurred while performing the operation","errorCode":null,"errors":null}
```

We have seen this across multiple extensions. Manually uploading via the Partner Center is still functional.

**To Reproduce**
Follow the steps to upload an extension package using the API outlined at https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api
1. Upload a package
2. Attempt to retrieve the status of the upload operation via `/v1/products/$productID/submissions/draft/package/operations/$operationID`
3. See that the response is `"status":"Failed"`, but with no `errorCode` or `errors` listed.

**Expected behavior**
A response containing `"status":"InProgress"` or `"status":"Suceeded"`, or at very least some information about the errors encountered.

**Desktop (please complete the following information):**
 - OS: macOS/Linux
 - Browser: Edge (or `curl` or `nodejs` for the API

**Additional context**
We have seen this across two different `$productID` values.

**Comment by MaximeHeckel** [comment]
Same here!

Tried with `@plasmohq/edge-addons-api` or manually with `fetch` in Node.js (on macOS) carefully following the [documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#checking-the-status-of-a-package-upload) and it's giving me the same error

We had the issue since July 12th on our end, and it's been blocking our automated release pipeline

**Comment by MaximeHeckel** [comment]
@yvsubhash just tried now and was able to push a draft 

Thank you for the quick fix!

**Comment by breadgrocery** [comment]
I have also encountered this problem. The draft was uploaded and verified successfully, but the publish failed, with the same response result and error message as yours. 
However, it can be published manually and successfully with just one click on the `Publish` button in the dashboard page.
