### ISSUE TITLE
[Bug - Partner Center] Certification fails because it cannot process zip file

### ISSUE THREAD

**Issue by mymindstorm** [microsoft/MicrosoftEdge-Extensions#176]
**Describe the bug**

I am trying to submit the MV3 version of our extension to partner center and am running into the below certification error message:

>   The package authenticator-7.0.0.zip is taking a long time to process. If this isn’t completed soon, try refreshing the page, or remove the package and then upload it again. If you continue to see this issue, contact support.

**Additional context**

![image](https://github.com/user-attachments/assets/db67b509-27dd-441a-be81-410e2e54d727)

Product ID: `ab9fa8d1-b5a8-4832-bfdb-aece55a87af7`

**Comment by ManikanthMSFT** [comment]
Hi @mymindstorm, thank you for reporting this. We are currently looking into the issue and will update you as soon as we have more information.

**Comment by mymindstorm** [comment]
@ManikanthMSFT could we get an update on this? We have critical updates that need to go out within the next week or two and this will be a blocker.

**Comment by ManikanthMSFT** [comment]
@mymindstorm, thank you for your patience. Could you please provide us with the package you are submitting to our support email (ext_dev_support@microsoft.com)? Once we receive the information, we will be able to assist you further.

Also, as a reference could you please mention #176 on your email.
