### ISSUE TITLE
[Bug - Partner Center] Manifest validation error for valid "world": "MAIN" property in content_scripts

### ISSUE THREAD

**Issue by ouweiya** [microsoft/MicrosoftEdge-Extensions#180]
**Describe the bug**
The Microsoft Partner Center is throwing a validation error for a legitimate `"world": "MAIN"` property in the `content_scripts` array of the manifest file. This property is part of the standard Web Extensions API and should be accepted.

**To Reproduce**
1. Go to the Microsoft Edge Addons developer dashboard
2. Attempt to upload a browser extension with a manifest file containing `"world": "MAIN"` in the `content_scripts` array
3. Observe the validation error

**Expected behavior**
The manifest file should be accepted without errors, recognizing `"world": "MAIN"` as a valid property in `content_scripts`.

**Screenshots**
![image](https://github.com/user-attachments/assets/a88db049-ea0c-4a4f-8dad-18d71a165d61)

**Error message**
```
The following checks failed:
Package acceptance validation error: The manifest shouldn't contain the key field.
Warnings:
Package acceptance validation warning: Only the following properties are allowed in the object: matches, exclude_matches, css, js, match_about_blank, run_at, all_frames, include_globs, exclude_globs, permissions, content_security_policy. Code: content_scripts[0].world: MAIN Line: 21 Column: 20
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 127

**Additional context**
The `"world": "MAIN"` property in `content_scripts` is a valid part of the Web Extensions API, used to specify the JavaScript world in which the content script should run. It's supported by major browsers including Chrome and Firefox. This validation error in the Edge Addons website prevents developers from using this legitimate feature in their extensions.

**References**
- [Chrome Developers documentation on content_scripts](https://developer.chrome.com/docs/extensions/reference/api/scripting#type-ExecutionWorld)
- [MDN Web Docs on content_scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts)

**Comment by ManikanthMSFT** [comment]
Hi @ouweiya,

Thank you for reporting this. We are looking into this and will let you know as soon as we have an update.

**Comment by ouweiya** [comment]
Hi @ManikanthMSFT 

Thanks for your work on this issue. 👋

I'm reaching out about the timeline for this bug fix. It's become a blocker for us:
- We can't release a new version
- Our update process is stalled

Could you share an estimated timeframe for the fix? This would really help with our release planning.

Let me know if you need any more info from our side to help resolve this. Happy to provide whatever's needed.

Thanks in advance for your help on this! 🙏

**Comment by ouweiya** [comment]
@ManikanthMSFT

Hello Manikanth,

I'm following up on the issue we previously discussed.

I wanted to inform you that I attempted to replicate the scenario again today, and unfortunately, the problem still persists. I was wondering if there have been any developments or progress made regarding this issue since our last communication.

Additionally, I would greatly appreciate any new suggestions or valuable information you might be able to provide to help address this ongoing concern.

**Comment by ManikanthMSFT** [comment]
Hey @ouweiya, to better assist you, could you please provide us with your zip package? You can send it to our email address [ext_dev_support@microsoft.com]. Our engineering team will review it and get back to you with the necessary assistance.
