### ISSUE TITLE
Published Extension not visible on US Market

### ISSUE THREAD

**Issue by waseem-omar** [microsoft/MicrosoftEdge-Extensions#182]
Hi Support,

I have submitted my extension to Edge Store, selected US as one of the markets under Availability section. Although the extension page states that it is Live, When searching for it from the US it does not show up in the search results https://microsoftedge.microsoft.com/addons/search/lucidretail

This is my extension page 
https://microsoftedge.microsoft.com/addons/detail/odjognldhfeabeigohocngoanibfhcmh

Thank you,
Waseem.

**Comment by ManikanthMSFT** [comment]
Hi @waseem-omar, thank you for reporting this. We are looking into this and will let you know as soon as we have an update.

**Comment by ManikanthMSFT** [comment]
Hi @waseem-omar, we have thoroughly tested the extension and found no issues accessing it from the United States store.

You can find it using this link: [LucidRetail Lite.](https://microsoftedge.microsoft.com/addons/search/LucidRetail%20Lite?hl=en-US&gl=US)

<img width="906" alt="image" src="https://github.com/user-attachments/assets/6622ab99-982e-4f34-81e1-834bd25acd5d">

If you have any further concerns, please feel free to reach out.

**Comment by waseem-omar** [comment]
This is so weird, it still does not appear in search results, although it is accessible via direct link.

<img width="1728" alt="Screenshot 2024-08-21 at 5 30 52 PM" src="https://github.com/user-attachments/assets/dabb54f2-2573-4b13-a25d-586f1749a9fa">

Thank you for looking into this!

**Comment by waseem-omar** [comment]
Here is a recording of what I am seeing. After around 10 refreshes to page, it showed up, then if you refresh again it goes away, then shows up again after I do many refreshes.

One more issue we are seeing, is that auto complete is not showing results related to our extension when typing "lucid...", although it shows relevant results when typing "adblock...".

Could you please check the recording and the screenshots below?


https://github.com/user-attachments/assets/77745249-f48a-43ff-97dd-98eb36443e43

![Screenshot 20240821104457@2x](https://github.com/user-attachments/assets/0bcb205b-5971-483e-b4db-fcac4b5be83c)
![Screenshot 20240821104505@2x](https://github.com/user-attachments/assets/71ff09e2-cc8d-4ae0-88ab-6ff8446eedf6)

**Comment by ManikanthMSFT** [comment]
Hey @waseem-omar, could you please navigate to **_Help -> Change Language or Region_**, set the region to **_United States_**, and then try again to see if your extension appears?

<img width="327" alt="image" src="https://github.com/user-attachments/assets/fa4168fc-8944-4afb-9fbd-b4383477e9c2">

**Comment by ManikanthMSFT** [comment]
Hey @waseem-omar, you can change your region from the extension [[main page](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home)] .

**Help -> Change Language or Region,** set the region to **United States**, and then try again to see if your extension appears?

<img width="920" alt="image" src="https://github.com/user-attachments/assets/15b26f1f-55ba-410c-b116-1abe85fa2bc5">
