### ISSUE TITLE
Please help expedite the extension review

### ISSUE THREAD

**Issue by ReginaHsu** [microsoft/MicrosoftEdge-Extensions#183]
Hi Microsoft,

We've submitted a review request for this Edge extension - [Synology Image Assistant Extension](
https://microsoftedge.microsoft.com/addons/detail/llplnibcahdpinjkofckooolpbcpilnn).
It will be very helpful if we can get the status update from you by this Friday, since the tool is expected to be available in 5 days.

Could you help with updating the review schedule for us by tomorrow? We'd like to make a schedule change if necessary.
Thank you and best regards,

Synology

**Comment by ManikanthMSFT** [comment]
Hey @ReginaHsu, we appreciate your patience.

Your expedited testing request is completed and has passed certification. 

Your submission is proceeding through the system and will typically be published within the hour, though it may take up to 24 hours.

Please reach out to us if you need any more assistance! Appreciate your patience 😊
