### ISSUE TITLE
create Developer Partner 

### ISSUE THREAD

**Issue by jasonLeeHaha** [microsoft/MicrosoftEdge-Extensions#186]
![Uploading screencapture-partner-microsoft-com-en-us-dashboard-Registration-AccountInfo-1724775306152.png…]()

**Comment by jasonLeeHaha** [comment]
![screencapture-partner-microsoft-com-en-us-dashboard-Registration-AccountInfo-1724775306152](https://github.com/user-attachments/assets/95070126-3855-4337-a8e5-de237879ab67)

**Comment by jasonLeeHaha** [comment]
![Uploading screencapture-partner-microsoft-com-en-us-dashboard-Registration-AccountInfo-1724775306152.png…]()

**Comment by ManikanthMSFT** [comment]
Hi @jasonLeeHaha, thank you for reporting this. We are looking into this and will let you know as soon as we have an update.

**Comment by jasonLeeHaha** [comment]
problem remained,please fix it ! thank you
![screencapture-partner-microsoft-com-en-us-dashboard-Registration-AccountInfo-1724775306152](https://github.com/user-attachments/assets/cd574cda-a6ad-4431-8468-060d2ace355a)

**Comment by jasonLeeHaha** [comment]
问题始终还是存在，具体详见附件。








---- Replied Message ----
| From | ***@***.***> |
| Date | 8/28/2024 12:54 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [microsoft/MicrosoftEdge-Extensions] create Developer Partner (Issue #186) |

Hi @jasonLeeHaha, thank you for reporting this. We are looking into this and will let you know as soon as we have an update.

**Comment by ManikanthMSFT** [comment]
Hi @jasonLeeHaha , we appreciate your patience. We have received an update from our team advising account holders to create an SR ticket using the [Partner Center](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpartner.microsoft.com%2Fen-us%2Fsupport%3Fstage%3D1&data=05%7C02%7Cv-ymanikanth%40microsoft.com%7C029090a799854726977408dcde19e4d8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638629450038419937%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qDbCZVyO0zIqaN%2FID9vp788iJi%2BgB1aBKLl5jQyBd4I%3D&reserved=0). This will route you to the appropriate team best suited to address your concerns.
