### ISSUE TITLE
[Bug - Partner Center] No response received for long time after I supplied document 

### ISSUE THREAD

**Issue by jliu1992** [microsoft/MicrosoftEdge-Extensions#188]
**Describe the bug**
My developer account registration fails at employment verification step which request me to upload domain purchase invoices or registry confirmation records. Finally I got the document and submitted on 19th Aug. It says 3-5 business days required but no any response till now.

Mail address for account registration: ui.ts.cmb@outlook.com

![Screenshot_2024-08-30-16-11-51-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/eba796f9-13fc-4458-aa2f-299b8c808f01)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ManikanthMSFT** [comment]
Hi @jliu1992, thank you for reaching out to us. We have received your query and are currently investigating it. If we require any further details, we will contact you. Otherwise, we will provide you with an update as soon as possible.

We appreciate your patience and will be in touch shortly.

**Comment by jliu1992** [comment]
@ManikanthMSFT May I have any updates please? It is blocking our project progress. Thanks.

**Comment by jliu1992** [comment]
Hi @ManikanthMSFT. Thanks. My account verification just now passed and authorized. Will close this ticket.
