### ISSUE TITLE
[FeatureReq - Partner Center] Changing publisher name

### ISSUE THREAD

**Issue by avi12** [microsoft/MicrosoftEdge-Extensions#189]
**Is your feature request related to a problem? Please describe.**
Recently I've been rebranding my name from "avi12" to "Avi" wherever I could

**Describe the solution you'd like**
The Edge dashboard should have an easy way to change the publisher name

**Describe alternatives you've considered**
I tried scouring around the dashboard settings and preferences to hopefully find a place where I could change the publisher name but, I couldn't

**Comment by ManikanthMSFT** [comment]
Hi @avi12, it is possible to change the publisher's name in the Edge dashboard, but you will need to undergo an additional review and re-submit your apps with the new publisher's name. Here are the general steps:

1. Sign in to [Partner Center](https://partner.microsoft.com/dashboard/home) and select the Settings (gear) icon.

2. Select Account settings, then Legal info > Developer tab, and then select [Legal info (microsoft.com)](https://partner.microsoft.com/dashboard/account/v3/organization/legalinfo#developer).

3. Scroll down to expand the Contact info section.

4. Select Update next to Contact info and change the details.

5. When you select Save, your legal identity will be reassessed. We only reassess information that you've changed.

![image](https://github.com/user-attachments/assets/64b83c9e-277e-4651-9471-c86a4874a77d)

**Comment by avi12** [comment]
Thank you for these steps. This was not very intuitive to get into before you told me
