### ISSUE TITLE
The tooltip of extension action icons with badges is incorrect.

### ISSUE THREAD

**Issue by carlosjeurissen** [microsoft/MicrosoftEdge-Extensions#19]
Currently in Microsoft Edge, the badge text is added as suffix to the tooltip of an extension action icon. This behavior is different from other browsers like Google Chrome, Firefox and Safari. See screenshot below.

To make sure extension developers have full control over the tooltip text, and to have the same experience as other browsers, this suffix should be removed.

In the past, it's mentioned this is done for accessibility reasons. However, it seems possible to still let screenreaders announce the badge text while the tooltip doesn't display the badge text (as it's already displayed on the badge).

See also:
https://github.com/w3c/webextensions/issues/32 
and
https://feedbackportal.microsoft.com/feedback/idea/24c872b5-a786-ec11-a81b-6045bd8295cb

![126125005-55d4ea57-1719-4353-a367-1fc2111a8155](https://user-images.githubusercontent.com/1038267/168272500-dcd3c3f5-3a5e-4ed3-a906-8695761e8f3e.png)

**Comment by nagachaitanyalokam** [comment]
Our engineers are looking into this issue.

**Comment by konossow** [comment]
Facing the same issue! 
Not sure if its related, but badge text color is different on Chrome and Edge. Even on 'dark' background text is in black.
Chrome: 
![image](https://user-images.githubusercontent.com/18230332/190854539-910d0ace-7d3a-42b5-b5e8-a81d24f38b41.png)
Edge:
![image](https://user-images.githubusercontent.com/18230332/190854553-249cabe2-0b35-4fab-9f04-ca016f1fb199.png)
Color used as bagde background: #008d55

**Comment by hanguokai** [comment]
@konossow This is another issue. You can add a new issue with details.

And this problem is present in both browsers. Chrome will support `setBadgeTextColor()`, see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1337783).

**Comment by hanguokai** [comment]
Thanks for fixing it!

**Comment by ManikanthMSFT** [comment]
@hanguokai, we are delighted to hear that your issue has been resolved. Should you encounter any further concerns or require additional assistance, please do not hesitate to reach out to us. We are always here to support you.
