### ISSUE TITLE
Extension Rejection - Unknown how to resolve

### ISSUE THREAD

**Issue by jackiesweet** [microsoft/MicrosoftEdge-Extensions#193]
We’ve recently tried to submit our Extension for approval with Edge but it got rejected and I’d like to understand how I can provide the input that is being requested.

The report details I received as reason for rejection as as follows:
1.1.5 Distinct Function & Value; Accurate Representation	
The store listing for the extension is not informative of the extension’s features and functionality. 

1.3 Product is Testable	
Unfortunately, we can't test the extension because its primary functionality is unclear. Please provide more information or steps to test in the Submission Options > Notes for Certification field when the extension is resubmitted.

What I don’t understand is where I’m actually supposed to provide the additional information Microsoft is requesting. Where is Submission Options > Notes for Certification?

I don’t see that going through any of the steps for submitting the extension for review.

**Comment by ManikanthMSFT** [comment]
Hey @jackiesweet, to assist you further, could you please provide your seller ID? This will help us verify your account and provide more accurate support.

Looking forward to your response!

**Comment by jackiesweet** [comment]
@ManikanthMSFT Where is the seller id? I followed this: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/manage-settings and I do not have a developer settings menu option. The store ID is 0RDCKBVR5K93

**Comment by ManikanthMSFT** [comment]
@jackiesweet, thank you for providing us with the store ID. We will investigate the issue and will get back to you with an update.

**Comment by jackiesweet** [comment]
@ManikanthMSFT  just wanted to follow up on the status of this

**Comment by bhuvanapriyap** [comment]
Hi @jackiesweet,

Regarding your certification results.

1.1.5 There should be distinct and informative details about your extension and its functionality in the listing (metadata) for your extension.

- Please provide more informative details about your extensions functionality. 

1.3 Your extension must be fully testable, and all the steps required for testing the product must be provided at the time of submission.

Please follow the guidelines here https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#step-6-complete-your-submission 
to complete and submit your extension

**Comment by jackiesweet** [comment]
@bhuvanapriyap this doesn't answer my original question. how can i find the notes for certification page? i can't find it anywhere
