### ISSUE TITLE
发布插件中验证公司的信息

### ISSUE THREAD

**Issue by jasonLeeHaha** [microsoft/MicrosoftEdge-Extensions#203]
![image](https://github.com/user-attachments/assets/711bb5e6-4c99-4061-8147-79d48d2712bc)
下一步该怎么办

**Comment by ManikanthMSFT** [comment]
Hi @jasonLeeHaha, we noticed that you have contacted us with the same query via email, and we have responded there. If you have any further questions, could we continue our conversation through that email thread?

**Comment by jasonLeeHaha** [comment]
可以通过邮件联系，你可以帮我解决这个问题嘛？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月01日 20:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [microsoft/MicrosoftEdge-Extensions] 发布插件中验证公司的信息 (Issue #203) |

Hi @jasonLeeHaha, we noticed that you have contacted us with the same query via email, and we have responded there. If you have any further questions, could we continue our conversation through that email thread?

**Comment by ManikanthMSFT** [comment]
Thank you for reaching out. We have already sent a solution to the email address you previously used to contact us. Please check your inbox, and if you need further assistance or did not receive the email, feel free to let us know.
