### ISSUE TITLE
[Bug - Partner Center] Unable to publish extension update due to unexpected error

### ISSUE THREAD

**Issue by ThomasGreiner** [microsoft/MicrosoftEdge-Extensions#207]
---
name: Bug report on Partner Center (impacting all developers)
about: Create a report to let us of any breaking issues or bugs that all Edge Addons
  developers are facing when publishing their extension to Microsoft Edge Addons
title: "[Bug - Partner Center] Unable to publish extension update due to unexpected error"
labels: Bug, Partner Center
assignees: nagachaitanyalokam

---

**Describe the bug**
When attempting to publish a new extension version, after a few minutes of waiting, a vague error messages is shown:
> We came across an unexpected error while trying to process your request. Please try again later

Neither the page's JavaScript console nor the network requests that are being made during those few minutes expose any additional information about what kind of error occurred.

**To Reproduce**
1. Go to https://partner.microsoft.com/en-us/dashboard/microsoftedge/overview
2. Click on the extension that you want to update
3. Click on "Update" button
4. Click on "Replace" link
5. Upload the new extension update
6. Click "Continue" button
7. Click "Publish" button
8. Click "Publish" button
9. Wait until the page no longer shows a loading indicator (usually takes a few minutes)
10. See error: _"We came across an unexpected error while trying to process your request. Please try again later"_
11. Go back to "Extension overview" page
12. Click "Publish" button next to extension version marked as "In draft"
13. Repeat steps (8) to (13)

**Expected behavior**
- Step (9) should take less than a minute to complete
- Step (10) should not show an error message, but instead show a message indicating that the extension was published successfully
  - Otherwise: The publishing should at least succeed after two or three retries.
- Steps (11) to (13) should not be necessary

**Screenshots**
![Image](https://github.com/user-attachments/assets/7bba4d3e-46ff-4745-8199-361be1271450)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 129

**Additional context**
When publishing new updates for the Adblock Plus for Microsoft Edge extension, we have encountered this problem every once in a while, but it seems to be occurring more frequently recently and it is currently so persistent that we are unable to publish the Adblock Plus 4.8 version to the Microsoft Edge extension store.

**Comment by ThomasGreiner** [comment]
@nagachaitanyalokam It looks like the issue meta data wasn't applied and I can't update it after the fact either. I assume I did something wrong there, but I hope it's not a big deal, and thought I'd ping you this way instead.

**Comment by ManikanthMSFT** [comment]
Hey @ThomasGreiner, thank you for reporting this issue. Could you please try reuploading your extension as this might be an intermediate issue? If you still encounter any problems, feel free to write back to us.

**Comment by ThomasGreiner** [comment]
@ManikanthMSFT Thank you for the quick reply and for the suggestion.

I have reuploaded the extension now by replacing the extension file in the "In draft" version, and the problem still persists even after multiple attempts to publish the extension.

**Comment by ManikanthMSFT** [comment]
Hey @ThomasGreiner, Thank you for your confirmation. We are looking into this and will let you know as soon as we have an update.

**Comment by JWorthe** [comment]
Hi @ManikanthMSFT. We're now trying to upload the next version of Adblock Plus and we're still running into this bug. Is there any feedback on getting this resolved?

**Comment by montrosb** [comment]
@ManikanthMSFT Here's a screenshot of the error message we received today.  It appears to be the same issue that Thomas reported 2 weeks ago.

![Image](https://github.com/user-attachments/assets/42601809-8951-4484-a79f-35d87d2b7c01)

**Comment by ThomasGreiner** [comment]
@ManikanthMSFT Sure, no problem. Here's the seller ID that's shown under Account settings > Organization profile > Legal info > Legal business profile > Account details: 26403930

**Comment by ManikanthMSFT** [comment]
Hi @ThomasGreiner, we appreciate your patience. We see that you submitted an extension, and it got published in the store yesterday. If you have any further questions or concerns, please don’t hesitate to contact us.
