### ISSUE TITLE
[FeatureReq - Partner Center] Employment verification

### ISSUE THREAD

**Issue by fgxtrue** [microsoft/MicrosoftEdge-Extensions#214]
**Is your feature request related to a problem? Please describe.**
Microsoft Partner Account Employment verification has been Rejected.But the information I provided is complete.
My account: aihome.chat@outlook.com
﻿
**Describe the solution you'd like**
I have submitted feedback through the back-end and support center, but have not received a response.
﻿
**Describe alternatives you've considered**
Please review the materials I submitted and approve the Employment verification. Thank you 
﻿
**Additional context**
My domain: aihome.chat
My company: si chuan xing li ke ji you xian gong si（四川星力科技有限公司）
Domain whois: screenshot from https://www.whois.com/whois/aihome.chat
[aihome.pdf](https://github.com/user-attachments/files/17537067/aihome.pdf)

**Comment by ManikanthMSFT** [comment]
Hey @fgxtrue, we request you to please create an SR ticket using the [Partner Center](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpartner.microsoft.com%2Fen-us%2Fsupport%3Fstage%3D1&data=05%7C02%7Cv-ymanikanth%40microsoft.com%7C029090a799854726977408dcde19e4d8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638629450038419937%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qDbCZVyO0zIqaN%2FID9vp788iJi%2BgB1aBKLl5jQyBd4I%3D&reserved=0). This will route you to the appropriate team best suited to address your concerns.
