### ISSUE TITLE
Urgent help to revert extension package upload

### ISSUE THREAD

**Issue by LOCOTA** [microsoft/MicrosoftEdge-Extensions#220]
Hello, 

I have 2 extensions developed by my Company:
1. " Panaya Test Automation", ID:  bbejbghccebkkldiblfnmaoojikndnib
2. "Panaya Recorder for Web Applications", ID:  lclmdbmkngbbpgafnhkkfepkandfdnbm

I did a mistake and uploaded an updated package zip of  bbejbghccebkkldiblfnmaoojikndnib into  lclmdbmkngbbpgafnhkkfepkandfdnbm

This was approved today - and thus customers cannot work with  lclmdbmkngbbpgafnhkkfepkandfdnbm

If I upload a fixed package - it would take up to a week for you to approve....
So may I ask if you can revert to the old package?
Or if not - can I get your help to quicklly get approve for a fixed package I will upload?

Much thanks,
Hadas Toronchik, 
panaya.rd@gmail.com

R&D TL
Panaya

**Comment by ManikanthMSFT** [comment]
Hey @LOCOTA, could you please upload the correct package and contact us via [email](ext_dev_support@microsoft.com)? We will review and assist you accordingly.

Thank you!

**Comment by LOCOTA** [comment]
Thanks for your respose!
I uploaded the correct package and sent an email to ext_dev_support@microsoft.com
(I did that yesterday after I understood that the email was the correct way to go)
Title of the email: "Urgent help needed to fix a corrupted extension package upload"
please approve that it was recieved, if possible.
