### ISSUE TITLE
[FeatureReq - Partner Center] Email Notification When the Extension is Approved

### ISSUE THREAD

**Issue by jjj201200** [microsoft/MicrosoftEdge-Extensions#230]
I don't seem to see an option in the publishing console to set an email address for receiving notifications about successful publication.

Is it possible to provide a way to receive such notifications, similar to the Chrome publishing console, so that I can respond promptly to the successful publishing status?

**Comment by Juraj-Masiar** [comment]
See also https://github.com/microsoft/MicrosoftEdge-Extensions/issues/181

**Comment by jjj201200** [comment]
Thx~
