### ISSUE TITLE
[Bug - Edge Addons] 1.1 Publish API Auth Error

### ISSUE THREAD

**Issue by aklinker1** [microsoft/MicrosoftEdge-Extensions#231]
**Describe the bug**
I'm trying to migrate my project to use the new authentication setup for publishing extensions, v1.1, as described here: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1#overview-of-using-the-update-rest-api

However, when I attempt to upload a new ZIP using the `POST /v1/products/$productID/submissions/draft/package` endpoint, I get a 401 error message:

```
Request: https://api.addons.microsoftedge.microsoft.com/v1/products/<my-product-id>/submissions/draft/package
Response: { "statusCode": 401, "message": "Invalid Azure AD JWT" }
```

I've tried creating new tokens, using both the old 1.0 client ID and the new 1.1 client ID (that was generated when enabling the v1.1 API), but nothing worked. I can confirm that the product ID in the URL is correct as well, if I just replace the headers with the old 1.0 headers, everything works fine. So it's got to be something to do with my headers.

Here they are, for reference:

```
Authorization: ApiKey <any-of-my-api-keys>
X-Client-ID: <new-client-id>
Content-Type: application/zip
```

All my API keys contain a `$` or `!` character, which sometimes requires escaping, but I've logged the values being sent, and they have been escaped properly.

**To Reproduce**
```sh
$ export PRODUCT_ID='...'
$ export API_KEY='...'
$ export CLIENT_ID='...'
$ curl -v -X POST https://api.addons.microsoftedge.microsoft.com/v1/products/$PRODUCT_ID/submissions/draft/package \
    -H "Authorization: ApiKey $API_KEY" \
    -H "X-Client-ID: $CLIENT_ID" \
    -T extension.zip
*   Trying 20.72.73.155:443...
* Connected to api.addons.microsoftedge.microsoft.com (20.72.73.155) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=api.addons.microsoftedge.microsoft.com
*  start date: Oct  2 13:38:39 2024 GMT
*  expire date: Sep 27 13:38:39 2025 GMT
*  subjectAltName: host "api.addons.microsoftedge.microsoft.com" matched cert's "api.addons.microsoftedge.microsoft.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 08
*  SSL certificate verify ok.
* using HTTP/1.x
> POST /v1/products/$PRODUCT_ID/submissions/draft/package HTTP/1.1
> Host: api.addons.microsoftedge.microsoft.com
> User-Agent: curl/8.4.0
> Accept: */*
> Authorization: ApiKey $API_KEY
> X-Client-ID: $CLIENT_ID
> Content-Length: 418
>
* We are completely uploaded and fine
< HTTP/1.1 401 Unauthorized
< Content-Length: 56
< Content-Type: application/json
< Request-Context: appId=cid-v1:23f44029-850d-47f4-8c9f-200d01ff4866
< Date: Thu, 05 Dec 2024 14:27:39 GMT
<
* Connection #0 to host api.addons.microsoftedge.microsoft.com left intact
{ "statusCode": 401, "message": "Invalid Azure AD JWT" }
```

**Expected behavior**
ZIP is uploaded successfully.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A (curl request)
 - Version: Sonoma 14.2.1

**Additional context**
Obviously, not gonna share any real values here, but that will probably make this difficult to investigate. 

Created this issue after sending an email and being asked to create an issue here for tracking purposes.

**Comment by ManikanthMSFT** [comment]
Hi @aklinker1, thank you for contacting us. We have already noted your query, and our team is on it. We will update you once we get an update.

**Comment by yvsubhash** [comment]
@aklinker1 Header for client id is X-ClientID In your list of headers X-Client-ID is given. Can you please correct the same and try again

**Comment by aklinker1** [comment]
🤦 Thanks, that did it.
