### ISSUE TITLE
Manifest file reference does not exist in zip archive

### ISSUE THREAD

**Issue by idoshamun** [microsoft/MicrosoftEdge-Extensions#236]
Hi!

For the first time in years, we started receiving this error when uploading our zip file.
![Image](https://github.com/user-attachments/assets/a1f29b8b-c62d-46ee-a6f3-964817399696)

We're not sure how to solve it and we even tried submitting old zip files that used to work and now they don't pass the validation step.
The same zip files are accepted on Chrome by the way.
I'd love to get some help.

Thanks a lot!

**Comment by aiktb** [comment]
Bro, I submitted the work order to them six months ago, but nothing was solved.

The average reply is once every two weeks, and the last reply was more than a month ago

Microsoft is a joke

**Comment by aiktb** [comment]
I want to know when you first discovered this issue. Isn't it common to everyone since about six months ago?

**Comment by carlosjeurissen** [comment]
@idoshamun can you share one of the zip files which fails to get through validation?

**Comment by idoshamun** [comment]
[Here you go](https://github.com/user-attachments/files/18218142/chrome.zip)

**Comment by carlosjeurissen** [comment]
@idoshamun not sure what the validator is doing here. But it might be triggered by the `name` / `short_name` including a pipe and url. Just to test `homepage_url`, I have added a leading slash at the end. Can you try the following modified zip?
[chrome-modified.zip](https://github.com/user-attachments/files/18218172/chrome-modified.zip)

**Comment by carlosjeurissen** [comment]
Seems to be related to: https://github.com/microsoft/MicrosoftEdge-Extensions/issues/235

**Comment by carlosjeurissen** [comment]
As mentioned here: https://github.com/microsoft/MicrosoftEdge-Extensions/issues/235#issuecomment-2558095389, including an empty file like I did in the chrome-modified.zip is a temporary workaround until this issue is fixed.

**Comment by idoshamun** [comment]
Thanks a lot, it works!
