### ISSUE TITLE
[Bug - Edge Addons API] Uploading a lesser version is possible

### ISSUE THREAD

**Issue by avi12** [microsoft/MicrosoftEdge-Extensions#26]
**Describe the bug**
The version of my extension that's published to the store is 1.5.1.
I discovered that, unlike the web-based dashboard, the [Upload API](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#uploading-a-package-to-update-an-existing-submission) doesn't check the versions.
In my case, I was able to upload version 1.3.15 and did not get any issues.

**To Reproduce**
Steps to reproduce the behavior: upload a ZIP of a version less than the currently-published version.

**Expected behavior**
Return an error object stating that the version is lesser.

**Screenshots**
![image](https://user-images.githubusercontent.com/6422804/169692911-89a93f10-2c6f-4d68-8916-389276bcc1c8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 x64  21H1

**Additional context**
If this behavior is intended, then there should at least be an API that allows for checking the extension's version.

**Comment by yvsubhash** [comment]
@avi12  This behavior is in line with UI. In the UI we are validating during publish step after upload. In case of api, the publish step is handled by the 'publish' operation. Please try publishing this extension and the version would be validated during publish operation

**Comment by avi12** [comment]
I see
Why is the validation step not occurring in the upload step?

**Comment by yvsubhash** [comment]
Even in the UI the behavior same, we check only when the publish operation is attempted. To be in sync with UI, validation is not done in the upload step for the version

**Comment by avi12** [comment]
I understood. I was asking why is this behavior like so out of curiosity

**Comment by yvsubhash** [comment]
it is primarily a design choice made with performance considerations during upload from UI

**Comment by nagachaitanyalokam** [comment]
Thanks @yvsubhash for the details!
