### ISSUE TITLE
Which version of edge is used in validation tests?

### ISSUE THREAD

**Issue by hanguokai** [microsoft/MicrosoftEdge-Extensions#29]
Sometimes browser adds new features in next version. Developers can use beta or canary version of Edge to develop these new features in extensions. But when publishing to Partner Center, the extension need to pass validation tests.

My question is which version of edge is used in validation tests?
If it only use current stable version of Edge, the extension may fail to pass tests because it depends on features in next stable version.

On Chrome, developers can set a ["minimum_chrome_version"](https://developer.chrome.com/docs/extensions/mv3/manifest/#:~:text=minimum_chrome_version) field in manifest.json, e.g. "minimum_chrome_version": "102". And can submit the extension to Chrome Web Store **before** next stable version release.

**Comment by nagachaitanyalokam** [comment]
our engineering is currently looking into this. We'll update you with the details soon.

**Comment by nagachaitanyalokam** [comment]
Our moderation team uses the current stable version of Edge or min version mentioned by the developer in the certification notes, while submitting the extension for review. Allowing developers to develop new features based on the upcoming updates to be released in next stable version that are already in canary version of Microsoft Edge
