### ISSUE TITLE
[Bug - Partner Center] Delay in Analytics Dashboard

### ISSUE THREAD

**Issue by AlmostOpensource** [microsoft/MicrosoftEdge-Extensions#30]
_**Describe the bug**_
As per the Partner Centre Analytics Dashboard for Edge Extensions, it is mentioned "_This data is made available with a 2 day delay._" But the data provided is delayed for 5 days. ie. Today is 10th Jun'22, but on my dashboard I can see data till 5th Jun'22. 

_**To Reproduce**_
Steps to reproduce the behaviour:
1. Go to 'Partner Centre' > 'Your published Extension'
2. Click on 'Analytics' > 'Weekly Users'
3. See error (Find the screenshot below)

_**Expected behaviour**_
This data is very vital to our product, I ask to have minimum delay of 1 day.

_**Screenshots**_

_**Desktop Details:**_
 - iOS
 - Brave Browser
 - V1.39.12 Version

_**Image:**_
<img width="1235" alt="Screenshot 2022-06-10 at 9 19 11 AM" src="https://user-images.githubusercontent.com/105704138/172987010-ad173b35-3e1e-4957-b545-be0a6259cb76.png">

**Comment by nagachaitanyalokam** [comment]
The dashboard is performing as expected. It will update every Tuesday (2 days after prev week ends). We are updating the messaging on Partner Center to reflect the same. We are also tracking another request ([[FeatureReq - Edge Addons site] Update Addon statistics daily · Issue #34 · microsoft/MicrosoftEdge-Extensions (github.com)](https://github.com/microsoft/MicrosoftEdge-Extensions/issues/34)) separately which is about making the data available more real time
