### ISSUE TITLE
[Bug - Partner Center] Error when trying to upload my extension update package (  Your package failed certification. Make corrections and certify again. )

### ISSUE THREAD

**Issue by st333v** [microsoft/MicrosoftEdge-Extensions#36]
**Describe the bug**
When i try and upload my extension "F.B.(FluffBusting)Purity"  update package, i get the following error message:

"The package 2.0_0.zip is taking a long time to process. If this isn’t completed soon, try refreshing the page, or remove the package and then upload it again. If you continue to see this issue, contact support."

I have tried refreshing the page many times, and tried uploading many times, but i just get the same error message each time, which is why im contacting you now. This error message is quite vague, i have no idea why the package is failing certification or why its taking "too long to upload" its all a mystery, Tbe other issue is the error message is not actually accurate about what actions can be takem as it suggests removing the package and then uploading it again, but that option is not actually available, the only action that can be taken is to either drag a new package onto the page, or click the "replace" link which just opens a file dialog which lets you do functionally the same thing, i.e upload the package again, but it just leads to the same error message again.

**To Reproduce**
1. Go to  https://partner.microsoft.com/en-us/dashboard/microsoftedge/ (the partner center dashboard page)
2. Click on Packages
3. Drag and drop extension package onto the page'
4. See error "The package 2.0_0.zip is taking a long time to process. If this isn’t completed soon, try refreshing the page, or remove the package and then upload it again. If you continue to see this issue, contact support."

**Expected behavior**
It should upload correctly and let me submit it for review and approval.

**Screenshots**
See attached screenshot

**Desktop (please complete the following information):**
 - OS:  windows 10
 - Browser chrome 
 - Version 103.0.5060.66 (Official Build) (32-bit)

**Additional context**
I have not changed much in the extension package recently, so at a loss as to why its failing, any help would be appreciated. 

![fhFaM7pGrX50Sfkz](https://user-images.githubusercontent.com/165368/176930148-eb64fe09-5b1b-48fd-bcd3-8bd9f93808a9.png)

**Comment by NabokD** [comment]
I have the same issue with the latest PocketTube! It looks like some bug on the Partner Center side because I have not changed my extension much too.

**Comment by st333v** [comment]
Sorry to hear you are suffering this issue too, but glad to know its not just me.

**Comment by nagachaitanyalokam** [comment]
Our engineering team is currently investigating the issue and I'll keep you posted on the status here.

**Comment by sonakshimore** [comment]
Adding comments on behalf of [@cyyynthia_](https://twitter.com/cyyynthia_) who is facing the same issue:

**Link to the issue shared:**
https://twitter.com/cyyynthia_/status/1543941345450098689

**Screenshot:**
![image](https://user-images.githubusercontent.com/85096285/177310871-e5a8a6d2-7bf3-48a8-9894-4874e2ac69a1.png)

**Comment by NabokD** [comment]
It seems fixed. I've uploaded the new version successfully. Thank you so much!

**Comment by varaduMSFT** [comment]
Thanks @NabokD for noticing that - yes, this issue is now fixed
