### ISSUE TITLE
[Bug - Partner Center]  The "contact us" link on the "About"  popup (accessed via the settings cog/gear icon in the top bar doesn't work

### ISSUE THREAD

**Issue by st333v** [microsoft/MicrosoftEdge-Extensions#37]
**Describe the bug**
  The "contact us" link on the "About"  popup (accessed via the settings cog/gear icon in the top bar doesn't work. when the contact us link is clicked, it just directs you to the bing search engine.

**To Reproduce**
1. click the settings button (gear icon) in the top black bar
2. click the "About"  menu  option / link
3. click the "Contact us" link
4. get redirected to the bing search engine (not very helpful)

**Expected behavior**
it should go to a contact page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version 103.0.5060.66 (Official Build) (32-bit)
 - 
**Additional context**
was going round in circles trying to contact you about a bug i was experiencing, had to dm someone i know who works at microsoft, and he told me about this github page, otherwise i would be none the wiser and still going round in circles

**Comment by nagachaitanyalokam** [comment]
Our engineering team is now investigating the issue. Will keep you posted on the status. Thanks

**Comment by nagachaitanyalokam** [comment]
We confirm the issue is resolved, please create a new issue in case of any challenges. Thank you!
