### ISSUE TITLE
[FeatureReq - Edge Addons site] Ability to report misconduct in user reviews on a Microsoft Edge Add-on product detail page

### ISSUE THREAD

**Issue by sonakshimore** [microsoft/MicrosoftEdge-Extensions#38]
**Is your feature request related to a problem? Please describe.**
The reviews posted on Microsoft Edge Add-on product detail page are not monitored for misconduct or rude, hateful & abusive behaviour in the reviews posted by users.

**Describe the solution you'd like**

**Comment by varaduMSFT** [comment]
Duplicate of https://github.com/microsoft/MicrosoftEdge-Extensions/issues/39
