### ISSUE TITLE
Input Search Problem

### ISSUE THREAD

**Issue by AsarAman** [microsoft/MicrosoftEdge-Extensions#52]
On a desktop view whenever we click on the search input it gives weired border which looks very bad to the eyes and whenever we scroll to the middle of the page the search input goes completely unresponsive.

**Comment by nagachaitanyalokam** [comment]
Hey @AsarAman Could you help us with more details? Are you referring to issue with Edge Add-ons site?

**Comment by AsarAman** [comment]
I am referring to microsoft browser, in which there is a main search input in the middle of the page i am talking about that one. Whenever we focus on the search input it has some bad looking border and when we scroll down it becomes unresponsive.

**Comment by nagachaitanyalokam** [comment]
Thanks for the details @AsarAman 

This community space is to help developers with Edge add-ons development journey and handling issues related to Partner Center and Microsoft Edge Add-ons site. 

For browser related issue, please reach out to Microsoft Edge support by following the steps mentioned [here](https://www.bing.com/ck/a?!&&p=29d9e5192184afc1JmltdHM9MTY2MzYzMjAwMCZpZ3VpZD0xYmMwMDczZS0yZWUzLTY3OTItM2E2My0xNmMwMmYwYjY2NzUmaW5zaWQ9NTQ1Mg&ptn=3&hsh=3&fclid=1bc0073e-2ee3-6792-3a63-16c02f0b6675&psq=where+is+help+and+feedback+on+microsoft+edge&u=a1aHR0cHM6Ly9hbnN3ZXJzLm1pY3Jvc29mdC5jb20vZW4tdXMvbWljcm9zb2Z0ZWRnZS9mb3J1bS9hbGwvaG93LXRvLXJlcG9ydC1hLWZlZWRiYWNrYnVnLXRvLW1pY3Jvc29mdC1lZGdlcy8yMGNjOGViNS0xMWJiLTQzYjYtOTVkMS1lMDA0ZDQxZWY4NzYjOn46dGV4dD1UaGVuJTIweW91JTIwbWF5JTIwb3BlbiUyME1pY3Jvc29mdCUyMEVkZ2UlMjBhbmQlMjBpbiwlMjh5b3UlMjBtYXklMjBvcGVuJTIwdGhpcyUyMG1lbnUlMjBieSUyMHByZXNzaW5nJTIwQWx0JTJCU2hpZnQlMkJJLg&ntb=1).
