### ISSUE TITLE
[Bug - Partner Center] Certification email mentions Microsoft 365 App Store instead of Edge Add-ons Store

### ISSUE THREAD

**Issue by infinitepower18** [microsoft/MicrosoftEdge-Extensions#60]
**Describe the bug**
The certification email that comes when an extension passed certification mentions the Microsoft 365 App Store and not the Edge Store. Moreover, the [documentation link](https://learn.microsoft.com/en-us/azure/marketplace/why-publish) in the email points to information about the Microsoft 365 store which seems unrelated to Edge.

**To Reproduce**
Submit an extension for review

**Expected behavior**
Email should say extension has passed certification for publication to the MS Edge Add-ons Store

**Screenshots**

<img width="503" alt="image" src="https://user-images.githubusercontent.com/44692189/195591208-0105b01f-dac2-4336-91f0-3a051faab64f.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22621.674
 - Browser: Microsoft Edge
 - Version: 106.0.1370.42 64 bit

**Comment by sivsouvamMSFT** [comment]
Thank you @infinitepower18 for sharing the bug. We have shared it with our engineering team. 

We will keep you posted on it.

**Comment by sivsouvamMSFT** [comment]
Thank you @hanguokai for reaching out to us.

Could you please share the product name?

**Comment by hanguokai** [comment]
@sivsouvamMSFT the extension id is igdedjplfplcnjadndfonimkmfjgfdjd on Edge store.
In the past, the attention note is included in the email. Now it is a report link, but I can't visit it.

**Comment by sivsouvamMSFT** [comment]
Thank you @hanguokai for sharing the detailed info. We will share it with our engineering team.
And will keep you posted on it.

**Comment by sivsouvamMSFT** [comment]
Hi @infinitepower18, regarding the published report issue while the certification was completed, it takes up to 2 hours to publish the extension. Going forward if you see this issue persists even after 2 hours, please let us know.

**Comment by infinitepower18** [comment]
@sivsouvamMSFT I wasn't talking about that. This issue is about the certification email referring to the wrong store (MS 365 App Store) instead of the Edge Extension store.

**Comment by sivsouvamMSFT** [comment]
Hi @infinitepower18, thank you for mentioning it. We are tracking this bug and shall be updating you once it is fixed

**Comment by ManikanthMSFT** [comment]
Hello, we appreciate your patience. We got an update from our team stating that now the certification emails are showing as edge instead of Microsoft 365 App Store.
