### ISSUE TITLE
Edge documentation says that extension has been moved to V3, but it hasn't

### ISSUE THREAD

**Issue by captainbrosset** [microsoft/MicrosoftEdge-Extensions#62]
This was originally filed here: MicrosoftDocs/edge-developer/issues/2264

See this documentation: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?tabs=v3 

It starts with:

> To see the completed extension package source for this part of the tutorial, go to [MicrosoftEdge-Extensions repo > extension-getting-started-part2](https://github.com/microsoft/MicrosoftEdge-Extensions/tree/main/Extension%20samples/extension-getting-started-part2/extension-getting-started-part2).
> The source code has been updated from Manifest V2 to Manifest V3.

But that's not true, if you follow that link, it leads to this repo, which contains a manifest v2, not v3.

**Comment by sivsouvamMSFT** [comment]
Thank you @captainbrosset for bringing it here.

Apologies for the inconvenience faced by the developer. We will look into it & make the necessary changes in the docs.

**Comment by sivsouvamMSFT** [comment]
Hi @captainbrosset, we have updated it. You can find the Manifest Version 3 sample code [here].(https://github.com/microsoft/MicrosoftEdge-Extensions/tree/main/Extension%20samples)
