### ISSUE TITLE
Transfer ownership of extensions

### ISSUE THREAD

**Issue by drveresh** [microsoft/MicrosoftEdge-Extensions#74]
The very important, basic, and yet most fundamental feature of transferring (ownership) extensions between users is missing for ages, and request you expedite this with a concrete plan and action.

Ref - [Edge-Extensions/discussions/15](https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/15)

I have been chasing this since 2019, with countless emails, calls, follow-ups, etc., and always getting fooled by your team with false promises.  Every possible extension and app store has had this basic feature from Day 1 since 2010 onwards, and I do not understand why your team is either deliberately ignoring it or miserably failing to understand this feature, and yet taking absolutely no action.

We are now in 2023 and 13+ years passed already, I strongly urge your team to put an end to this!

**Comment by drveresh** [comment]
@nagachaitanyalokam @sonakshimore 
Can you please let your entire extension team proactively respond to queries, emails, and issues? I seriously do not see their commitment and responsibility to act on the real issues. I dealt with more than 15 folks from your Extension team, and everybody stopped to respond to emails, are their emails working or dead?

Most importantly, now I need your help to expedite this issue!

**Comment by sivsouvamMSFT** [comment]
Hi @drveresh, we understand the need for the feature. Our team is working on it, as mentioned earlier over call & email by our team members to you. Highly apprieciate your patience with us. We shall be soon updating your more on it.

**Comment by drveresh** [comment]
@sivsouvamMSFT @sonakshimore  The words "**understand**, **working**, **earlier**, **soon**, **patience**.." are really losing their meaning, intent, and deosn't seem to make no difference to your team because none of them lead or concluding to anything at all.  I have been hearing the same words and statements since 2019, and what makes you think they make a difference now?

The W3 Consortium team members rebuilding web technologies and adding next generation of features every single day!  But, your team is going no where on this rudimentary feature since years, in spite of reusing the copy of chromium project.

In sum, can you please share the realistic and concrete updates and timeline?

**Comment by sivsouvamMSFT** [comment]
Hey @drveresh, I wanted to let you know that we have been giving thoughtful consideration to the request for this feature. Our team is actively working on it and I would be happy to keep you updated on the progress as we move forward. I am confident that by June 2023, you will start to see some meaningful developments and I look forward to the opportunity to share these with you.

**Comment by f-eli-pe** [comment]
+1 on this. I have no way to transfer an extension from one account to the other. Edge support told me to simply republish the extension on the new account, which I tried doing, and was rejected because a similar extension was already on the Edge store. 🙃

**Comment by sivsouvamMSFT** [comment]
Hey @f-eli-pe, could you please email us at ext_dev_support@microsoft.com with your Seller ID & extension CRX-ID, stating our conversation here? I will look into it & come up with the best solution for you.

**Comment by f-eli-pe** [comment]
> Hey @f-eli-pe, could you please email us at ext_dev_support@microsoft.com with your Seller ID & extension CRX-ID, stating our conversation here? I will look into it & come up with the best solution for you.

Just did, @sivsouvamMSFT thank you 🙏

**Comment by f-eli-pe** [comment]
If anyone was wondering, they still weren't able to help. Might give up, hard to start from scratch when there's a clone of my app already on the store gaining traction. 

Seems like the Edge Add-on store is still in beta and Microsoft forgot to tell us 😜

**Comment by fetch-lab** [comment]
> Hey @drveresh, I wanted to let you know that we have been giving thoughtful consideration to the request for this feature. Our team is actively working on it and I would be happy to keep you updated on the progress as we move forward. I am confident that by June 2023, you will start to see some meaningful developments and I look forward to the opportunity to share these with you.

Hi @sivsouvamMSFT, it's July 2023 now, any update?

**Comment by drveresh** [comment]
@varaduMSFT @sivsouvamMSFT As per our discussions, this feature should have been available by now.  How long your team is going to release this basic feature? Please share the concrete details.

**Comment by cmdlinebeep** [comment]
@sivsouvamMSFT 
Agree with everyone here.  This ability is basic and a decade overdue, and now 6 months past Microsoft's own Summer '23 deadline.  Is there an update on this?  Thank you for any updates you can share.

**Comment by drveresh** [comment]
@varaduMSFT @sivsouvamMSFT @fetch-lab Absolutely no response from you since last year (Jul 4, 2023) on this open issue.  What is happening? Your team has been fooling everyone, at least me since 2019 about fake promises and timelines.  How long you need to deliver this single feature?

**Comment by sandeepchads** [comment]
Hi, we are in beta testing of transfer of ownership. @drveresh  thank you for raising this bug and we hope you are unblocked.

We request other developers who may be facing this issue to drop us an email at "ext_dev_support@microsoft.com"

**Comment by sivMSFT** [comment]
Hi @openchampagne & @cmdlinebeep,

Could you please share your extension details here over [email](mailto:[ext_dev_support@microsoft.com])? We have already started the beta testing for the feature "Transfer of Ownership".

**Comment by ManikanthMSFT** [comment]
Hello, we are pleased to inform you that we now have a stable and streamlined process for transferring ownership of accounts. If you wish to initiate a transfer, please reach out to us directly to our [email]([ext_dev_support@microsoft.com]).

Our team will guide you through the process and assist you with any queries you may have.

Thank you for your patience and continued support as we improved this feature. We look forward to assisting you.

**Comment by Mohamed3nan** [comment]
> Hello, we are pleased to inform you that we now have a stable and streamlined process for transferring ownership of accounts. If you wish to initiate a transfer, please reach out to us directly to our [email](%5Bext_dev_support@microsoft.com%5D).
> 
> Our team will guide you through the process and assist you with any queries you may have.
> 
> Thank you for your patience and continued support as we improved this feature. We look forward to assisting you.

I sent an email 10 days ago and have not received any response yet
