### ISSUE TITLE
[FeatureReq - Partner Center] Improve documentation on "detailed guide to configuring extensions using the ExtensionSettings policy"

### ISSUE THREAD

**Issue by middletonk** [microsoft/MicrosoftEdge-Extensions#76]
**Is your feature request related to a problem? Please describe.**
I'd like to know how to replicate the "allow extension in InPrivate" checkbox using JSON as incompletely described in the [detailed guide to configuring extensions using the ExtensionSettings policy](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide).

**Describe the solution you'd like**
I'd like the documentation on the product to be complete, please and thanks. 

**Describe alternatives you've considered**
I've considered giving up.

**Additional context**
I already submitted this as direct article feedback from the documentation page itself and [and was instructed to come here](https://github.com/MicrosoftDocs/Edge-Enterprise/issues/194).

**Comment by sivMSFT** [comment]
Hi @middletonk, apologies the request was missed out. 

Could you please share more info about the article feedback? We are unable to find the link to it.
