### ISSUE TITLE
Emails asking for surveys should have an unsubscribe link

### ISSUE THREAD

**Issue by xPaw** [microsoft/MicrosoftEdge-Extensions#79]
Today I received a "Microsoft Edge Add-ons – Take this 2-minute survey on Microsoft Partner Center", and it contains the following: "You are receiving this email because we identified you as a browser extension developer. Please reply to this email with the subject “Unsubscribe” if you do not want to receive these types of communications."

So I tried to reply, but the email was denied:
> <msftpc@microsoft.com>: host
    microsoft-com.mail.protection.outlook.com[104.47.53.36] said: 550 5.4.1
    Recipient address rejected: Access denied. AS(201806281)

**Comment by sivsouvamMSFT** [comment]
Hi @xPaw, thank you for bringing it up to us.  We will look into it & update you on it.

**Comment by sivsouvamMSFT** [comment]
Hi @xPaw, you can opt out of such emails from Microsoft Partner Center by making changes to your Email Notification Preferences. Please follow the [documentation](https://learn.microsoft.com/en-gb/partner-center/action-center-overview#preferences) to opt out.

**Comment by xPaw** [comment]
And which category do surveys fall under? These survey emails should include a link to unsubscribe then too.

**Comment by sivsouvamMSFT** [comment]
@xPaw, these survey emails come under the insights workspace.

Regarding your suggestion about adding an unsubscribe link in the email, we appreciate your feedback. We will take note of this suggestion and work on incorporating the above information in future communications.

Thank you for your valuable feedback, and please do not hesitate to reach out to us if you have any further concerns.
